apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rorpage-owm
  namespace: openfaas-fn
spec:
  encryptedData:
    hmac-secret: AgDB6kwyrWQKyEl50cSXwgr6P1wULcGHitfMmr7zws4PzTJ4hyuleCc/RhIK47/RuddI3AZC/FH9h4ZPNUy7D7f2EbUtMwzonMKvGR17r6qVMGdXok1JIveNFzBSbyH17W6ejWFtcqx15WDSd6xxzxVX6k82dBfX9Dez+j6Yl4pIp8qWOj93v2JdqVBtjWV16wAM6KyO0J2HFsc6FB5kXfYqm+/DlDg95IjVq4D5CXtTvlvpwIdkv4MtVPMKE+dLM61BgaAjmSew693syDLg7KftxBJhmKcGh0yYbnLqNBGodyiw/s8eA2TapXqTG48omdE9AEZJVfRYMPaa6+1WFjlER8tdINsZDH2INHqDd4BTRo9kDc+2wpkPfiKNqa8e3m57GnXYn7XVftEINxEX4ouQ5C2PjLPfdJFB+E6r77nHm1gtR6iWQ6wkNCfug9aXoQI45HHbhWKhenp1i0Lb1KBXs4kSGDelkS/YAgy5p888V7Dg092x+FY3iXL7QmZz7PrE4JZ8+gzKZdVA3Q+bMAOvQ6ZYeTPkJJYNs0jJubQSdYCTRqGzbRJRp7ap3I58mk0i1K84QpzGHBpUSn5GiGl/BLA7XEO8rcsyUAuFY6jI8/HHHEuMTj+qJ4g4Hju1N3PEjWoOACGYwiG6c6cyNcRMMNCQxy2hIPPFkmremAxe5QsjzB/pzDoWAZ2OecTL0w8yoYCKi3LZUfQInLM7xdi0AOrYE0PWV2ZmT/7ZuabYXQ==

